image: Visual Studio 2017

platform:
  - x64~

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: '14'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build_script:
  - yarn build

test: off
